import React,{useEffect,useMemo,useState}from'react';
import{Bell,ChevronDown,Gift,History,Home,Menu,Play,PlayCircle,RotateCcw,Target,Trophy,UserRound,WalletCards,X,CheckCircle2,Clock3,LoaderCircle,ShieldCheck,Plus,Users,Flame,ArrowUpRight,Volume2}from'lucide-react';
import{ADS,GOAL}from'./data';
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
export default function App(){
 const[page,setPage]=useState('watch'),[open,setOpen]=useState(false),[watched,setWatched]=useState(load('watched',[])),[today,setToday]=useState(load('today',0)),[life,setLife]=useState(load('life',0)),[activity,setActivity]=useState(load('activity',[])),[selected,setSelected]=useState(null),[status,setStatus]=useState('idle'),[left,setLeft]=useState(0),[progress,setProgress]=useState(0);
 useEffect(()=>{save('watched',watched);save('today',today);save('life',life);save('activity',activity)},[watched,today,life,activity]);
 const available=useMemo(()=>ADS.filter(a=>!watched.includes(a.id)),[watched]);
 const watch=ad=>{setSelected(ad);setStatus('loading');setLeft(ad.duration);setProgress(0);setTimeout(()=>{setStatus('watching');let n=ad.duration;const t=setInterval(()=>{n--;setLeft(n);setProgress((ad.duration-n)/ad.duration*100);if(n<=0){clearInterval(t);setProgress(100);setStatus('completed');setWatched(x=>x.includes(ad.id)?x:[...x,ad.id]);setToday(x=>x+1);setLife(x=>x+ad.reward);setActivity(x=>[{id:Date.now(),...ad,time:'just now'},...x])}},1000)},650)};
 const close=()=>{setSelected(null);setStatus('idle');setLeft(0)};
 const reset=()=>{localStorage.clear();location.reload()};
 return <div className="shell">
  <aside className={open?'side open':'side'}><div className="brand"><div className="logo-mark">V</div><div><strong>VELOOP</strong><small>Rewards & Giveaways</small></div><button className="close" onClick={()=>setOpen(false)}><X/></button></div>
   <nav><button className={page==='home'?'active':''} onClick={()=>{setPage('home');setOpen(false)}}><Home/>Dashboard</button><button className={page==='watch'?'active':''} onClick={()=>{setPage('watch');setOpen(false)}}><PlayCircle/>Watch & Earn</button><button onClick={()=>setPage('bonus')} className={page==='bonus'?'active':''}><Gift/>Rewards</button><button onClick={()=>setPage('bonus')}><Trophy/>Giveaways</button><button onClick={()=>setPage('profile')} className={page==='profile'?'active':''}><UserRound/>Profile</button></nav>
   <div className="side-art"><div className="headphone">🎧</div><div className="script">Watch<br/>Earn<br/>Win</div><b>Your Time<br/><span>=</span><br/>Real Rewards</b></div>
  </aside>
  <main><header><div className="head-left"><button className="menu" onClick={()=>setOpen(true)}><Menu/></button><div className="welcome"><div className="avatar-group"><Users/></div><div><strong>Hello, Hansa Prajapat 👋</strong><small>Keep watching, keep earning!</small></div></div></div><div className="head-right"><Bell className="bell"/><div className="balance"><span>VE</span><b>{life?2450+life:2450}</b><Plus/></div><div className="profile-avatar">👩🏻</div><ChevronDown/></div></header>
   {page==='watch'?<section className="page">
    <div className="hero"><div className="hero-copy"><span className="new-badge">NEW</span><h1>Watch & Earn</h1><h2>Turn your time into rewards!</h2><p>Watch short ads, complete the timer and<br/>get VE coins instantly.</p><button className="hero-btn" onClick={()=>available[0]&&watch(available[0])}><Play fill="currentColor"/>Watch Now <Play fill="currentColor"/></button></div><div className="hero-visual"><div className="screen"><div>▶</div></div><div className="coin c1">VE</div><div className="coin c2">VE</div><div className="coin c3">VE</div><div className="clock-ring">◷</div><span className="ad-tag">AD</span><i>Earn<br/>More<br/>VE ↗</i></div></div>
    <div className="content-grid"><div className="main-col">
      <div className="stats"><div className="stat card"><div className="stat-icon"><Play/></div><span>Total Ads Watched</span><b>{watched.length} / 10</b><i><u style={{width:`${watched.length*10}%`}}/></i><small>{Math.max(0,10-watched.length)} more to complete today</small></div><div className="stat card green"><div className="stat-icon"><WalletCards/></div><span>Today's Earnings</span><b>+{today*15} VE ↗</b><small>+20% from yesterday</small></div><div className="stat card pink"><div className="stat-icon"><Flame/></div><span>Daily Streak</span><b>3 Days 🔥</b><small>Keep it up!</small></div><div className="stat card blue"><div className="stat-icon"><WalletCards/></div><span>Total Balance</span><b>{life?2450+life:2450} VE ↗</b><small>Your rewards are safe!</small></div></div>
      <div className="ads-heading"><div><h2><PlayCircle/>Available Ads</h2><p>Watch ads, complete the timer and earn VE coins.</p></div><span>{ADS.length} Unique Ads</span></div>
      <div className="ads">{ADS.map((a,i)=><article className={watched.includes(a.id)?'ad card done':'ad card'} key={a.id}><div className={`ad-visual ${a.tone}`}><em>{i+1}</em><small>◷ {a.duration}s</small><div className="ad-image">{a.icon}</div></div><div className="ad-body"><h3>{a.title}</h3><p><span>🪙</span> +{a.reward} VE</p><button disabled={watched.includes(a.id)} onClick={()=>watch(a)}>{watched.includes(a.id)?<><CheckCircle2/>Watched</>:<><Play fill="currentColor"/>Watch Now</>}</button></div></article>)}</div>
    </div><aside className="right-col"><div className="bonus-card card"><div className="gift-art">🎁</div><div><h3>Daily Bonus</h3><p>Claim your daily bonus<br/>and get extra VE</p><button onClick={()=>setPage('bonus')}>Claim Now →</button></div><span>›</span></div><div className="side-card card"><div className="side-card-title"><h3><Target/>Daily Progress</h3><a>View All</a></div><div className="progress-line"><i style={{width:`${Math.min(100,watched.length*10)}%`}}/></div><div className="progress-num">{watched.length}/10</div><p className="motivation">🚀 Great! You're almost there!</p></div><div className="side-card card activity"><div className="side-card-title"><h3><Clock3/>Recent Activity</h3><a>View All</a></div>{(activity.length?activity:[{id:1,reward:20,time:'2 mins ago'},{id:2,reward:25,time:'15 mins ago'},{id:3,reward:15,time:'32 mins ago'},{id:4,reward:30,time:'1 hour ago'}]).slice(0,4).map(x=><div className="activity-row" key={x.id}><CheckCircle2/><span>You earned <b>+{x.reward} VE</b></span><small>{x.time}</small></div>)}</div><div className="success-card"><div>🎁</div><h3>Congratulations!</h3><p>You earned <b>+25 VE</b><br/>from watching an ad</p><button onClick={()=>setPage('bonus')}>View Rewards</button></div></aside></div>
   </section>:<section className="page"><div className="bonus-page card"><Gift/><span>DAILY BONUS</span><h1>Keep your streak going</h1><p>Watch eligible advertisements each day and build progress toward your daily bonus reward.</p></div><div className="bonus-grid">{[1,2,3,4,5,6,7].map(d=><div className="card day" key={d}><small>DAY {d}</small><b>+{d===7?100:d*10} VE</b><span>{d===1?'Available today':'Complete previous day'}</span></div>)}</div></section>}
   <footer>© 2025 Veloop Rewards & Giveaways <span>|</span> Watch <span>•</span> Earn <span>•</span> Win <small>Small steps make big rewards ♥</small></footer>
   <button className="reset-fab" title="Reset demo" onClick={reset}><RotateCcw/></button>
  </main>
  {selected&&<div className="modal"><div className="watch-modal"><button className="modal-x" onClick={close}><X/></button>{status==='loading'&&<div className="state"><LoaderCircle className="spin"/><h2>Loading advertisement…</h2><p>Preparing your reward session.</p></div>}{status==='watching'&&<div className="state"><div className="fake">{selected.icon}<b>{selected.brand}</b><small>SPONSORED PREVIEW</small></div><div className="timer"><span>Watching advertisement</span><b>{left}s</b></div><div className="bar"><i style={{width:progress+'%'}}/></div><p>Please keep this window open until the timer reaches zero.</p></div>}{status==='completed'&&<div className="state"><div className="success">✓</div><h2>Reward successful!</h2><p>You earned <b>+{selected.reward} VE</b> for completing {selected.brand}.</p><span className="note"><ShieldCheck/>Reward added to your balance</span><button className="continue" onClick={close}>Continue</button></div>}</div></div>}
 </div>
}
